#
# Module manifest for module 'Microsoft.Graph.Groups'
#
# Generated by: Microsoft Corporation
#
# Generated on: 2/25/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Groups.psm1'

# Version number of this module.
ModuleVersion = '2.26.1'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '50bc9e18-e281-4208-8913-c9e1bef6083d'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.26.1'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Groups.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Groups.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgGroupFavorite', 'Add-MgGroupToLifecyclePolicy', 
               'Confirm-MgGroupGrantedPermissionForApp', 
               'Confirm-MgGroupMemberGroup', 'Confirm-MgGroupMemberObject', 
               'Confirm-MgGroupSettingTemplateMemberGroup', 
               'Confirm-MgGroupSettingTemplateMemberObject', 'Get-MgGroup', 
               'Get-MgGroupAcceptedSender', 'Get-MgGroupAcceptedSenderByRef', 
               'Get-MgGroupAcceptedSenderCount', 'Get-MgGroupById', 
               'Get-MgGroupByUniqueName', 'Get-MgGroupConversation', 
               'Get-MgGroupConversationCount', 'Get-MgGroupConversationThread', 
               'Get-MgGroupConversationThreadCount', 
               'Get-MgGroupConversationThreadPost', 
               'Get-MgGroupConversationThreadPostAttachment', 
               'Get-MgGroupConversationThreadPostAttachmentCount', 
               'Get-MgGroupConversationThreadPostCount', 
               'Get-MgGroupConversationThreadPostExtension', 
               'Get-MgGroupConversationThreadPostExtensionCount', 
               'Get-MgGroupConversationThreadPostInReplyToAttachment', 
               'Get-MgGroupConversationThreadPostInReplyToAttachmentCount', 
               'Get-MgGroupConversationThreadPostInReplyToExtension', 
               'Get-MgGroupConversationThreadPostInReplyToExtensionCount', 
               'Get-MgGroupCount', 'Get-MgGroupCreatedOnBehalfOf', 
               'Get-MgGroupDelta', 'Get-MgGroupExtension', 
               'Get-MgGroupExtensionCount', 'Get-MgGroupLifecyclePolicy', 
               'Get-MgGroupLifecyclePolicyByGroup', 
               'Get-MgGroupLifecyclePolicyCount', 'Get-MgGroupMember', 
               'Get-MgGroupMemberAsApplication', 'Get-MgGroupMemberAsDevice', 
               'Get-MgGroupMemberAsGroup', 'Get-MgGroupMemberAsOrgContact', 
               'Get-MgGroupMemberAsServicePrincipal', 'Get-MgGroupMemberAsUser', 
               'Get-MgGroupMemberByRef', 'Get-MgGroupMemberCount', 
               'Get-MgGroupMemberCountAsApplication', 
               'Get-MgGroupMemberCountAsDevice', 'Get-MgGroupMemberCountAsGroup', 
               'Get-MgGroupMemberCountAsOrgContact', 
               'Get-MgGroupMemberCountAsServicePrincipal', 
               'Get-MgGroupMemberCountAsUser', 'Get-MgGroupMemberGroup', 
               'Get-MgGroupMemberObject', 'Get-MgGroupMemberOf', 
               'Get-MgGroupMemberOfAsAdministrativeUnit', 
               'Get-MgGroupMemberOfAsGroup', 'Get-MgGroupMemberOfCount', 
               'Get-MgGroupMemberOfCountAsAdministrativeUnit', 
               'Get-MgGroupMemberOfCountAsGroup', 
               'Get-MgGroupMemberWithLicenseError', 
               'Get-MgGroupMemberWithLicenseErrorAsApplication', 
               'Get-MgGroupMemberWithLicenseErrorAsDevice', 
               'Get-MgGroupMemberWithLicenseErrorAsGroup', 
               'Get-MgGroupMemberWithLicenseErrorAsOrgContact', 
               'Get-MgGroupMemberWithLicenseErrorAsServicePrincipal', 
               'Get-MgGroupMemberWithLicenseErrorAsUser', 
               'Get-MgGroupMemberWithLicenseErrorCount', 
               'Get-MgGroupMemberWithLicenseErrorCountAsApplication', 
               'Get-MgGroupMemberWithLicenseErrorCountAsDevice', 
               'Get-MgGroupMemberWithLicenseErrorCountAsGroup', 
               'Get-MgGroupMemberWithLicenseErrorCountAsOrgContact', 
               'Get-MgGroupMemberWithLicenseErrorCountAsServicePrincipal', 
               'Get-MgGroupMemberWithLicenseErrorCountAsUser', 'Get-MgGroupOwner', 
               'Get-MgGroupOwnerAsApplication', 'Get-MgGroupOwnerAsDevice', 
               'Get-MgGroupOwnerAsGroup', 'Get-MgGroupOwnerAsOrgContact', 
               'Get-MgGroupOwnerAsServicePrincipal', 'Get-MgGroupOwnerAsUser', 
               'Get-MgGroupOwnerByRef', 'Get-MgGroupOwnerCount', 
               'Get-MgGroupOwnerCountAsApplication', 
               'Get-MgGroupOwnerCountAsDevice', 'Get-MgGroupOwnerCountAsGroup', 
               'Get-MgGroupOwnerCountAsOrgContact', 
               'Get-MgGroupOwnerCountAsServicePrincipal', 
               'Get-MgGroupOwnerCountAsUser', 'Get-MgGroupPermissionGrant', 
               'Get-MgGroupPermissionGrantCount', 'Get-MgGroupPhoto', 
               'Get-MgGroupPhotoContent', 'Get-MgGroupRejectedSender', 
               'Get-MgGroupRejectedSenderByRef', 'Get-MgGroupRejectedSenderCount', 
               'Get-MgGroupSetting', 'Get-MgGroupSettingCount', 
               'Get-MgGroupSettingTemplateById', 'Get-MgGroupSettingTemplateCount', 
               'Get-MgGroupSettingTemplateDelta', 
               'Get-MgGroupSettingTemplateGroupSettingTemplate', 
               'Get-MgGroupSettingTemplateMemberGroup', 
               'Get-MgGroupSettingTemplateMemberObject', 
               'Get-MgGroupSiteGetByPathApplicableContentTypeForList', 
               'Get-MgGroupSiteGetGraphBPrePathActivityByInterval', 
               'Get-MgGroupThread', 'Get-MgGroupThreadCount', 
               'Get-MgGroupThreadPost', 'Get-MgGroupThreadPostAttachment', 
               'Get-MgGroupThreadPostAttachmentCount', 
               'Get-MgGroupThreadPostCount', 'Get-MgGroupThreadPostExtension', 
               'Get-MgGroupThreadPostExtensionCount', 
               'Get-MgGroupThreadPostInReplyToAttachment', 
               'Get-MgGroupThreadPostInReplyToAttachmentCount', 
               'Get-MgGroupThreadPostInReplyToExtension', 
               'Get-MgGroupThreadPostInReplyToExtensionCount', 
               'Get-MgGroupTransitiveMember', 
               'Get-MgGroupTransitiveMemberAsApplication', 
               'Get-MgGroupTransitiveMemberAsDevice', 
               'Get-MgGroupTransitiveMemberAsGroup', 
               'Get-MgGroupTransitiveMemberAsOrgContact', 
               'Get-MgGroupTransitiveMemberAsServicePrincipal', 
               'Get-MgGroupTransitiveMemberAsUser', 
               'Get-MgGroupTransitiveMemberCount', 
               'Get-MgGroupTransitiveMemberCountAsApplication', 
               'Get-MgGroupTransitiveMemberCountAsDevice', 
               'Get-MgGroupTransitiveMemberCountAsGroup', 
               'Get-MgGroupTransitiveMemberCountAsOrgContact', 
               'Get-MgGroupTransitiveMemberCountAsServicePrincipal', 
               'Get-MgGroupTransitiveMemberCountAsUser', 
               'Get-MgGroupTransitiveMemberOf', 
               'Get-MgGroupTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgGroupTransitiveMemberOfAsGroup', 
               'Get-MgGroupTransitiveMemberOfCount', 
               'Get-MgGroupTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgGroupTransitiveMemberOfCountAsGroup', 
               'Invoke-MgForwardGroupConversationThreadPost', 
               'Invoke-MgForwardGroupConversationThreadPostInReplyTo', 
               'Invoke-MgForwardGroupThreadPost', 
               'Invoke-MgForwardGroupThreadPostInReplyTo', 'Invoke-MgGraphGroup', 
               'Invoke-MgRenewGroup', 'Invoke-MgReplyGroupConversationThread', 
               'Invoke-MgReplyGroupConversationThreadPost', 
               'Invoke-MgReplyGroupConversationThreadPostInReplyTo', 
               'Invoke-MgReplyGroupThread', 'Invoke-MgReplyGroupThreadPost', 
               'Invoke-MgReplyGroupThreadPostInReplyTo', 
               'Invoke-MgRetryGroupServiceProvisioning', 
               'Invoke-MgSubscribeGroupByMail', 'New-MgGroup', 
               'New-MgGroupAcceptedSenderByRef', 'New-MgGroupConversation', 
               'New-MgGroupConversationThread', 
               'New-MgGroupConversationThreadPostAttachment', 
               'New-MgGroupConversationThreadPostAttachmentUploadSession', 
               'New-MgGroupConversationThreadPostExtension', 
               'New-MgGroupConversationThreadPostInReplyToAttachment', 
               'New-MgGroupConversationThreadPostInReplyToAttachmentUploadSession', 
               'New-MgGroupConversationThreadPostInReplyToExtension', 
               'New-MgGroupExtension', 'New-MgGroupLifecyclePolicy', 
               'New-MgGroupMember', 'New-MgGroupMemberByRef', 'New-MgGroupOwner', 
               'New-MgGroupOwnerByRef', 'New-MgGroupPermissionGrant', 
               'New-MgGroupRejectedSenderByRef', 'New-MgGroupSetting', 
               'New-MgGroupSettingTemplateGroupSettingTemplate', 
               'New-MgGroupThread', 'New-MgGroupThreadPostAttachment', 
               'New-MgGroupThreadPostAttachmentUploadSession', 
               'New-MgGroupThreadPostExtension', 
               'New-MgGroupThreadPostInReplyToAttachment', 
               'New-MgGroupThreadPostInReplyToAttachmentUploadSession', 
               'New-MgGroupThreadPostInReplyToExtension', 'Remove-MgGroup', 
               'Remove-MgGroupAcceptedSenderDirectoryObjectByRef', 
               'Remove-MgGroupByUniqueName', 'Remove-MgGroupConversation', 
               'Remove-MgGroupConversationThread', 
               'Remove-MgGroupConversationThreadPostAttachment', 
               'Remove-MgGroupConversationThreadPostExtension', 
               'Remove-MgGroupConversationThreadPostInReplyToAttachment', 
               'Remove-MgGroupConversationThreadPostInReplyToExtension', 
               'Remove-MgGroupExtension', 'Remove-MgGroupFavorite', 
               'Remove-MgGroupFromLifecyclePolicy', 
               'Remove-MgGroupLifecyclePolicy', 
               'Remove-MgGroupMemberDirectoryObjectByRef', 
               'Remove-MgGroupOwnerDirectoryObjectByRef', 
               'Remove-MgGroupPermissionGrant', 'Remove-MgGroupPhoto', 
               'Remove-MgGroupPhotoContent', 
               'Remove-MgGroupRejectedSenderDirectoryObjectByRef', 
               'Remove-MgGroupSetting', 
               'Remove-MgGroupSettingTemplateGroupSettingTemplate', 
               'Remove-MgGroupThread', 'Remove-MgGroupThreadPostAttachment', 
               'Remove-MgGroupThreadPostExtension', 
               'Remove-MgGroupThreadPostInReplyToAttachment', 
               'Remove-MgGroupThreadPostInReplyToExtension', 
               'Reset-MgGroupUnseenCount', 'Restore-MgGroupSettingTemplate', 
               'Set-MgGroupLicense', 'Set-MgGroupPhotoContent', 
               'Test-MgGroupProperty', 'Test-MgGroupSettingTemplateProperty', 
               'Update-MgGroup', 'Update-MgGroupByUniqueName', 
               'Update-MgGroupConversationThread', 
               'Update-MgGroupConversationThreadPostExtension', 
               'Update-MgGroupConversationThreadPostInReplyToExtension', 
               'Update-MgGroupExtension', 'Update-MgGroupLifecyclePolicy', 
               'Update-MgGroupPermissionGrant', 'Update-MgGroupSetting', 
               'Update-MgGroupSettingTemplateGroupSettingTemplate', 
               'Update-MgGroupThread', 'Update-MgGroupThreadPostExtension', 
               'Update-MgGroupThreadPostInReplyToExtension'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Remove-MgGroupAcceptedSenderByRef', 'Remove-MgGroupMemberByRef', 
               'Remove-MgGroupOwnerByRef', 'Remove-MgGroupRejectedSenderByRef'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoPAYJKoZIhvcNAQcCoIIoLTCCKCkCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCB9Brb/s4VgqNwZ
# e+z0mLLUhf6uRXc9bpPsBoyLubeli6CCDYUwggYDMIID66ADAgECAhMzAAAEA73V
# lV0POxitAAAAAAQDMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTEzWhcNMjUwOTExMjAxMTEzWjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQCfdGddwIOnbRYUyg03O3iz19XXZPmuhEmW/5uyEN+8mgxl+HJGeLGBR8YButGV
# LVK38RxcVcPYyFGQXcKcxgih4w4y4zJi3GvawLYHlsNExQwz+v0jgY/aejBS2EJY
# oUhLVE+UzRihV8ooxoftsmKLb2xb7BoFS6UAo3Zz4afnOdqI7FGoi7g4vx/0MIdi
# kwTn5N56TdIv3mwfkZCFmrsKpN0zR8HD8WYsvH3xKkG7u/xdqmhPPqMmnI2jOFw/
# /n2aL8W7i1Pasja8PnRXH/QaVH0M1nanL+LI9TsMb/enWfXOW65Gne5cqMN9Uofv
# ENtdwwEmJ3bZrcI9u4LZAkujAgMBAAGjggGCMIIBfjAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU6m4qAkpz4641iK2irF8eWsSBcBkw
# VAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEWMBQGA1UEBRMNMjMwMDEyKzUwMjkyNjAfBgNVHSMEGDAW
# gBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIw
# MTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDEx
# XzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIB
# AFFo/6E4LX51IqFuoKvUsi80QytGI5ASQ9zsPpBa0z78hutiJd6w154JkcIx/f7r
# EBK4NhD4DIFNfRiVdI7EacEs7OAS6QHF7Nt+eFRNOTtgHb9PExRy4EI/jnMwzQJV
# NokTxu2WgHr/fBsWs6G9AcIgvHjWNN3qRSrhsgEdqHc0bRDUf8UILAdEZOMBvKLC
# rmf+kJPEvPldgK7hFO/L9kmcVe67BnKejDKO73Sa56AJOhM7CkeATrJFxO9GLXos
# oKvrwBvynxAg18W+pagTAkJefzneuWSmniTurPCUE2JnvW7DalvONDOtG01sIVAB
# +ahO2wcUPa2Zm9AiDVBWTMz9XUoKMcvngi2oqbsDLhbK+pYrRUgRpNt0y1sxZsXO
# raGRF8lM2cWvtEkV5UL+TQM1ppv5unDHkW8JS+QnfPbB8dZVRyRmMQ4aY/tx5x5+
# sX6semJ//FbiclSMxSI+zINu1jYerdUwuCi+P6p7SmQmClhDM+6Q+btE2FtpsU0W
# +r6RdYFf/P+nK6j2otl9Nvr3tWLu+WXmz8MGM+18ynJ+lYbSmFWcAj7SYziAfT0s
# IwlQRFkyC71tsIZUhBHtxPliGUu362lIO0Lpe0DOrg8lspnEWOkHnCT5JEnWCbzu
# iVt8RX1IV07uIveNZuOBWLVCzWJjEGa+HhaEtavjy6i7MIIHejCCBWKgAwIBAgIK
# YQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlm
# aWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
# OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYD
# VQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+la
# UKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc
# 6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4D
# dato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+
# lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
# kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6
# A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmd
# X4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
# 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zd
# sGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3
# T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS
# 4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRI
# bmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
# BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBD
# uRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jv
# c29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
# BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1h
# cnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkA
# YwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn
# 8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7
# v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0b
# pdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/
# KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvy
# CInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
# mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJi
# hsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYb
# BL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
# oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sL
# gOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtX
# cVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCGg0wghoJAgEBMIGVMH4x
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
# Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTECEzMAAAQDvdWVXQ87GK0AAAAA
# BAMwDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEINLM
# iiX97OGWT4k5MLwiJzn+mmXUivxGuODh48/XFJXlMEIGCisGAQQBgjcCAQwxNDAy
# oBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20wDQYJKoZIhvcNAQEBBQAEggEAltMtinTB4EB+HumyVd//NRBxSn3E5YlioPp1
# HoZEe3iS5Cmmp/rNaCDEQVhmR9SCT23kfVrU0orjsC+GT4fRIAMWRXOzfAg7Pj0+
# pRFDRhVr8P48VCtJZYW1oXBoQdpB3uUvT2/EUQnM/Pi9kDKpVvWW6usASwGeMJEA
# YUhprYAQj2HclGKYZ58l/Iwzj3Z4EWwixWmS7scaRF0OpqD8YIuNy2n/9dy2Pqqb
# tovur9hIX/ifHIogbd2o5M9AyZekaEkLAP4KPSXj4cKhSeMPlyBge0d4FNoJYf1S
# 87q4P8xfp6/3IXT/Jo3guwFvZ9f559DJDWVXUO9SqUH6zJgRgaGCF5cwgheTBgor
# BgEEAYI3AwMBMYIXgzCCF38GCSqGSIb3DQEHAqCCF3AwghdsAgEDMQ8wDQYJYIZI
# AWUDBAIBBQAwggFSBgsqhkiG9w0BCRABBKCCAUEEggE9MIIBOQIBAQYKKwYBBAGE
# WQoDATAxMA0GCWCGSAFlAwQCAQUABCDoiDfN0POuT93uNsnGOCzDMDsBpRG4jqdl
# rdKicQ/XKgIGZ7elLkWhGBMyMDI1MDIyNTIwMDQzNC40MjVaMASAAgH0oIHRpIHO
# MIHLMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQL
# ExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxk
# IFRTUyBFU046OEQwMC0wNUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1l
# LVN0YW1wIFNlcnZpY2WgghHtMIIHIDCCBQigAwIBAgITMwAAAg0Nd757No9/4wAB
# AAACDTANBgkqhkiG9w0BAQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAx
# MDAeFw0yNTAxMzAxOTQzMDFaFw0yNjA0MjIxOTQzMDFaMIHLMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1l
# cmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046OEQwMC0w
# NUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Uw
# ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCxf6gH3fH3wgmFN5TV8zRF
# /N0TJguWUYCrQZPUmwA+QhSySNp7kiGmFZd4b5zsAfN0Wh+PzIJvYsVMgVCaZcbV
# r/DJBfexwnQfc+fgIjOiAzYSjg7EtSOdWoLk81b/mGiGIBC++fLcSAzbZO3KtW4P
# RKOSsdD/5eRdtNca/Ed4EAcUT32zAGS9Sq//4kDT92KEzRNXJj8z3NDL4oGGzCQM
# vA83tQG5mrnepxF0OsNfKKHYHMqjyOEP5pTgKfT5XMfz0sEG6ARAjlXJ79SG/joe
# uHh8TqC+cJMry9wB7ZLrdMAFy8rHN3W1+kkpw47Ko+9ize2ble+P5jMaqufK033B
# u+2FXVSKphil2j0qBUWpn5vBtf2W+gsVqydA+eseBHfYxcDZ4+5oRoyDAg0tW9f7
# 9vOAv91P4bTzG+BZPBbDMzSDwmj8ASKDlVwruTeF1em7NWiedWAB+29gFH/c/NN1
# uTQLvwGDIOw1DcLnCD0VXNL7mOvifYvNWugTAHcMFLVlA1jeOH35E/IW9qcKKqra
# h7LyJax/6M5UHswQugGgLriiMNEvz3IqW+AiIJ097iYzMGzsDqbLSUztIjDEt9xf
# IHHUs/p3j9Bkr2bPP1v4z8vp/45Ck3mfFbW2F0EtjOCnGPMrJNjjGhEG9zAK1105
# Bg2kJ7Rn8WTWO5IbD/rDtQIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFBWXjpDmDgNr
# TsISj26SjU1/YMOAMB8GA1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8G
# A1UdHwRYMFYwVKBSoFCGTmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMv
# Y3JsL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBs
# BggrBgEFBQcBAQRgMF4wXAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0
# LmNvbS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUy
# MDIwMTAoMSkuY3J0MAwGA1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUH
# AwgwDgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4ICAQAcH8gT42wVQ8GQ
# Z+MHIXNJ+d4dQn0+vPG/AdFvTxk/tvOOkA2i7hnoEOEFcSbzS5EdIVCMi5Y5EiWT
# 8hEJkztdeq5hXtUWsPY+2lYSU9HdhKDfRDfjwVZ9kfCthrLRC3jw9Fah5MAGI9MH
# SETo9r7+cux8AUqQ3hmaM2jmTNWvrFOLbO01B1ciNGbvE2xK+rbzBBh/uWd3k30p
# au6Lp0azg7rDYGMGv8jWotILfpKMBeCQoufMsI/gzxo4+k9dqYBkAwMk7h1hf23y
# cb5WngSMQV/Uxl3Sxbg+64KK6GCsTSG6z7zNTgbL69PMGfwV2cnawY95Iy2cgJ6c
# bMORRUcYzvsuUd8oEQ87cW4XqqBLrheewJjROT6YyWrQ2oQ+jzGK2WJoGNnfanmN
# fqQnVKpi320onag95LMFjj8BwrflYsO9kEOiy7I5UngPBmF+RHSCv2hFSr8nK7gt
# uiy9SUOKP6FbQOzyMRvJ3UxsmrH38477XzETb/tZLAj10TdYFfkjkFeFjlb3iMTS
# s/VrJSF0r0vON/oxZqKCY8WZez+uQP0Try0QQ9wRp5D2FYJ8E1uIX/LvwuFkBdWf
# 7X7qlb+pzdvPpSAcaCgBIWTlMn2bWgkU5uPzxRPHh/0u+FI7/eRCZGbLM2qnn3yX
# QvO/h9wQm8pIABRAvodaiV0bVmHbETCCB3EwggVZoAMCAQICEzMAAAAVxedrngKb
# SZkAAAAAABUwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
# EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
# ZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmlj
# YXRlIEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIy
# NVowfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
# B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UE
# AxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEB
# AQUAA4ICDwAwggIKAoICAQDk4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXI
# yjVX9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjo
# YH1qUoNEt6aORmsHFPPFdvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1y
# aa8dq6z2Nr41JmTamDu6GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v
# 3byNpOORj7I5LFGc6XBpDco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pG
# ve2krnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg3viS
# kR4dPf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYr
# bqgSUei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlM
# jgK8QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSL
# W6CmgyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AF
# emzFER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIu
# rQIDAQABo4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIE
# FgQUKqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWn
# G1M1GelyMFwGA1UdIARVMFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEW
# M2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5
# Lmh0bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBi
# AEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV
# 9lbLj+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3Js
# Lm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAx
# MC0wNi0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2
# LTIzLmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv
# 6lwUtj5OR2R4sQaTlz0xM7U518JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZn
# OlNN3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1
# bSNU5HhTdSRXud2f8449xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4
# rPf5KYnDvBewVIVCs/wMnosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU
# 6ZGyqVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDF
# NLB62FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/
# HltEAY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdU
# CbFpAUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKi
# excdFYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTm
# dHRbatGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZq
# ELQdVTNYs6FwZvKhggNQMIICOAIBATCB+aGB0aSBzjCByzELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJp
# Y2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjhEMDAtMDVF
# MC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMK
# AQEwBwYFKw4DAhoDFQB7LCwoj6G3nQ7Oxhl/pfne4yATPaCBgzCBgKR+MHwxCzAJ
# BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
# MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jv
# c29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA62gSQTAi
# GA8yMDI1MDIyNTA5NTYxN1oYDzIwMjUwMjI2MDk1NjE3WjB3MD0GCisGAQQBhFkK
# BAExLzAtMAoCBQDraBJBAgEAMAoCAQACAgn4AgH/MAcCAQACAhJyMAoCBQDraWPB
# AgEAMDYGCisGAQQBhFkKBAIxKDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSCh
# CjAIAgEAAgMBhqAwDQYJKoZIhvcNAQELBQADggEBACQmuw0kcBDe4CkMaSezcTKg
# VUnYMYiSdLHl4K4i8oXWcdUlYOHy0cdcQ4fyD4CQn8TXHdHXi22JuXtt056tJvDx
# kfWvTNKSB315MkSWbRg46rzx+e9jBnVv1UZls2QdvP5J92JVhdSVIs0l88W+lGcP
# 2AMdGHu2NakQJQ5V2C70+xzx+vBFL1QsY0NOjrH7ccMvZzmUs0F5H7mkTTodtu9O
# OoiJyM71jDHmbqJ+hxqQsOOk0Jp9YtoK1DcyVsWk/1PNc9AgKnef5n4My+Uk8fHr
# 1W8EajuQOcqxyGsfqqEe3f9/em3McEuBiwTYF+hf40DmpjS29lWThzcEQ7CMJqwx
# ggQNMIIECQIBATCBkzB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
# bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
# aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAA
# Ag0Nd757No9/4wABAAACDTANBglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkD
# MQ0GCyqGSIb3DQEJEAEEMC8GCSqGSIb3DQEJBDEiBCC3PcfunYg8gRR+cb0sQ03v
# tzaclg3R1MMD+Q4xsQ6EgjCB+gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIGPq
# B5TsJGqI8OuknBKtSvb0Ffq6w5NSs5veTVwka/hAMIGYMIGApH4wfDELMAkGA1UE
# BhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
# BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0
# IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAINDXe+ezaPf+MAAQAAAg0wIgQgdly+
# IR9XRZcjPcyE1+bG2YE/jS7DWBfTCAF6eEn0lOswDQYJKoZIhvcNAQELBQAEggIA
# je2Q4LFtjiBWKYUYVk6Y3zVX3gpKwW79nFAN/+vE+BnUmKV8WnNyY4JMy8nK9GcL
# 7g5T207FrrgwwWHXpiEX7XEqxSXgvKCIRTBcCsvtAuPO0cAphUK8fSoM6GNPCOHu
# vah5H99ZDF1lOtR+i33UvJ8ij+j8Y7MVz0JkvnMBBKXfKHRWOkbJP2HDXIs9EmDm
# 1ZeP9E0zBxSfPCTnOl60TytXJ168c4a5wISmXH5CYOX3ZZJ67qtTW5KGkWRwDXtl
# btgojMndwMhBNvGNzADOHcKUFKHf3rk72kn2m80QKf28Z1rwqBMq4iuNtCA1IfsM
# aLLBloGH5yy4PONpBdHXN0UGsY7jrp9BgkMe1Pt6cla5u2dVsZ98/b+8iw/3/Azz
# cJ9pp6kUwg2JP8+k9Yf0NDPVHdxfZ5c1FsaVpUrci4WNjoNdhSOc9pj1tnw+nVm7
# UkwJ7P3UGQsdm1fS1VWptdaBEYWbp2GUspGVtUDDfpGHZcJcnGjFA2Qj+dkmDgnV
# 0VGj1xB2EZ0y1FWR5fRo2ke8xl7E3PykRZaWwvGuHxOGQNyKlWe50EFDjcE1yvOG
# /Y/8/past5J1fhqrFqTEqJvdKC8MZIkOtoAT0IX4SM9lhu4aza4730+irOQ2zggE
# zRE6TOt/3rBNZhF9KTokICi0pIhpKP2K3L7KRDbRLjE=
# SIG # End signature block
