class CAPWATCH_Member {
    [int]$CAPID
    [string]$SSN
    [string]$NameLast
    [string]$NameFirst
    [string]$NameMiddle
    [string]$NameSuffix
    [string]$Gender
    [datetime]$DOB
    [string]$Profession
    [int]$EducationLevel
    [string]$Citizen
    [string]$ORGID
    [string]$Wing
    [string]$Unit
    [string]$Rank
    [datetime]$Joined
    [datetime]$Expiration
    [datetime]$OrgJoined
    [string]$UsrID
    [datetime]$DateMod
    [string]$LSCode
    [string]$Type
    [datetime]$RankDate
    [string]$Region
    [string]$MbrStatus
    [string]$PicStatus
    [datetime]$PicDate
    [string]$CdtWaiver
    [string]$Ethnicity
}